### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fabiosun** [mdjabirov/pve-edge-kernel#1]
`root@proxmox:~/pve-edge-kernel# apt install make
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  make-doc
The following NEW packages will be installed:
  make
0 upgraded, 1 newly installed, 0 to remove and 523 not upgraded.
Need to get 396 kB of archives.
After this operation, 1,630 kB of additional disk space will be used.
Get:1 http://http.us.debian.org/debian testing/main amd64 make amd64 4.3-4 [396 kB]
Fetched 396 kB in 2s (193 kB/s)
Selecting previously unselected package make.
(Reading database ... 84469 files and directories currently installed.)
Preparing to unpack .../archives/make_4.3-4_amd64.deb ...
Unpacking make (4.3-4) ...
Setting up make (4.3-4) ...
Processing triggers for man-db (2.8.5-2) ...
root@proxmox:~/pve-edge-kernel# make
Using build type: zen2
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
make: dpkg-architecture: No such file or directory
rm -rf build/linux linux.prepared
mkdir -p build
cp -a submodules/linux build/linux
cp -a debian-kernel/debian debian-kernel/debian.master build/linux/
cat build/linux/debian.master/config/config.common.ubuntu build/linux/debian.master/config//config.common. build/linux/debian.master/config//config.flavour.generic > config-5.8.0.org
cat: build/linux/debian.master/config//config.common.: No such file or directory
cat: build/linux/debian.master/config//config.flavour.generic: No such file or directory
make: *** [Makefile:117: linux.prepared] Error 1
root@proxmox:~/pve-edge-kernel#`

I have this error. I do not know If I miss others things to do

**Comment by mdjabirov** [comment]
What happens when you try the 1st step in the pre-requisites items:

apt install build-essential asciidoc-base bison flex libdw-dev libelf-dev libiberty-dev libnuma-dev libslang3-dev libssl-dev lz4 xmlto zlib1g-dev dh-make dh-python lintian sphinx-common

**Comment by fabiosun** [comment]
![](https://www.macos86.it/uploads/monthly_2020_08/1712027663_ScreenShot2020-08-07at11_17_11.png.e5a360feda64568399371a501880e611.png)
I have this error

**Comment by mdjabirov** [comment]
Yep, that's a typo. It should be libslang2-dev. Try that. Fixing in the README. There could be other things as I did this pre-requisite installation a while ago. Appreciate catching it.

**Comment by fabiosun** [comment]
Ok I will do

**Comment by fabiosun** [comment]
<img width="1060" alt="Screen Shot 2020-08-07 at 21 11 39" src="https://user-images.githubusercontent.com/6358373/89680152-af1fbf00-d8f2-11ea-9a29-ae9ba8f2e6c8.png">
maybe have I start again from start?

**Comment by mdjabirov** [comment]
You run “make clean” to start from scratch. This will auto remove build folder.
